# Generated by Django 3.2 on 2021-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=600, null=True)),
                ('active_section', models.BooleanField(default=True)),
            ],
        ),
    ]
