# Generated by Django 3.2 on 2021-04-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='active_section',
        ),
    ]
