# Generated by Django 3.2 on 2021-04-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_about_active_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
