# Generated by Django 3.2 on 2021-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210415_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesections',
            name='cancel_about',
        ),
        migrations.RemoveField(
            model_name='activesections',
            name='cancel_contact',
        ),
        migrations.RemoveField(
            model_name='activesections',
            name='cancel_experience',
        ),
        migrations.RemoveField(
            model_name='activesections',
            name='cancel_portfolio',
        ),
        migrations.RemoveField(
            model_name='activesections',
            name='cancel_services',
        ),
        migrations.AddField(
            model_name='activesections',
            name='about',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='activesections',
            name='contact',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='activesections',
            name='experience',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='activesections',
            name='portfolio',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='activesections',
            name='services',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
